*** Keywords ***
Setup da minha suite de teste
    Log To Console    \n\n Estou executando minha função ANTES da suite de teste \n\n

Setup dos meus testes
    Log To Console    \n\n Estou executando minha função ANTES da execução do meu teste \n\n

Teardown da minha suite de teste
    Log To Console    \n\n Estou executando minha função DEPOIS da suite de teste  \n\n

Teardown dos meus testes
    Log To Console    \n\n Estou executando minha função DEPOIS da execução do meu teste \n\n